//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp28.NewFolder1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Bibl_dsrymarEntities : DbContext
    {
        public Bibl_dsrymarEntities()
            : base("name=Bibl_dsrymarEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Author> Author { get; set; }
        public virtual DbSet<Book> Book { get; set; }
        public virtual DbSet<Create_Build> Create_Build { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<History_Reader_Ticket> History_Reader_Ticket { get; set; }
        public virtual DbSet<Janr> Janr { get; set; }
        public virtual DbSet<Post> Post { get; set; }
        public virtual DbSet<Reader> Reader { get; set; }
        public virtual DbSet<ReadTicket> ReadTicket { get; set; }
    }
}
