//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp28.NewFolder1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Book()
        {
            this.History_Reader_Ticket = new HashSet<History_Reader_Ticket>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> ID_author { get; set; }
        public Nullable<int> Year_make { get; set; }
        public Nullable<int> ID_create_build { get; set; }
        public Nullable<int> ID_janr { get; set; }
        public Nullable<int> Count_Page { get; set; }
    
        public virtual Author Author { get; set; }
        public virtual Create_Build Create_Build { get; set; }
        public virtual Janr Janr { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<History_Reader_Ticket> History_Reader_Ticket { get; set; }
    }
}
