//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp28.NewFolder1
{
    using System;
    using System.Collections.Generic;
    
    public partial class History_Reader_Ticket
    {
        public int ID { get; set; }
        public Nullable<int> ID_Ticket { get; set; }
        public Nullable<int> ID_Book { get; set; }
        public Nullable<System.DateTime> Date_Start { get; set; }
        public Nullable<int> Date_End { get; set; }
        public string Comment { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual ReadTicket ReadTicket { get; set; }
    }
}
