//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp28.NewFolder1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReadTicket
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ReadTicket()
        {
            this.History_Reader_Ticket = new HashSet<History_Reader_Ticket>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ID_Employee { get; set; }
        public Nullable<int> ID_Reader { get; set; }
        public Nullable<System.DateTime> Date_Registr { get; set; }
        public Nullable<bool> isDelete { get; set; }
    
        public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<History_Reader_Ticket> History_Reader_Ticket { get; set; }
        public virtual Reader Reader { get; set; }
    }
}
